version: '2.0'
services:
  db:
    image: postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
  c9:
    image: kdelfour/cloud9-docker
    volumes:
      - .:/workspace/
    ports:
<<<<<<< HEAD
      - "8001:80"
=======
      - "8000:80"
>>>>>>> 0aa1578b87f28e77f858acaa545b408d0705d10e
    depends_on:
      - web
