# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 15:55
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('role', models.CharField(choices=[('Artist', 'Artist'), ('Organizer', 'Organizer'), ('Customer', 'Customer')], max_length=25, verbose_name='Role')),
                ('bank_account', models.CharField(max_length=34)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('artwork_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('art_type', models.CharField(max_length=30)),
                ('date', models.DateTimeField(default=datetime.date.today)),
                ('price', models.IntegerField()),
                ('state', models.PositiveIntegerField(blank=True, choices=[(1, 'Available'), (2, 'Displayed'), (3, 'Sold')], null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_by', to='ArtProject.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('role', models.CharField(choices=[('Artist', 'Artist'), ('Organizer', 'Organizer'), ('Customer', 'Customer')], max_length=25, verbose_name='Role')),
                ('bank_account', models.CharField(max_length=34)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('ini_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('artwork', models.ManyToManyField(blank=True, to='ArtProject.Artwork')),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('role', models.CharField(choices=[('Artist', 'Artist'), ('Organizer', 'Organizer'), ('Customer', 'Customer')], max_length=25, verbose_name='Role')),
                ('afiliation_CIF', models.CharField(blank=True, max_length=9)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtProject.Organizer'),
        ),
    ]
