# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-19 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('Painting', 'Painting'), ('Sculpture', 'Sculpture'), ('Photography', 'Photography')], max_length=25, null=True, verbose_name='Type'),
        ),
    ]
