# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-22 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='state',
            field=models.PositiveIntegerField(choices=[(1, 'Available'), (2, 'Displayed'), (3, 'Sold')], default=1),
        ),
    ]
