# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-23 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtProject', '0002_auto_20180522_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='art_type',
            field=models.CharField(blank=True, choices=[('Painting', 'Painting'), ('Sculpture', 'Sculpture'), ('Photography', 'Photography')], max_length=30, null=True, verbose_name='Type'),
        ),
    ]
